name: iOS Gdal build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13-xlarge

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install cmake
        brew install libtiff
        brew install libgeotiff
        brew install libpng
        brew install jpeg
        brew install qhull
        brew install liblerc
        brew install geos
        git clone https://github.com/leetal/ios-cmake.git $HOME/opt/ios-cmake

    - name: Copy toolchain file
      run: |
        mkdir -p $HOME/dev/3rdParty/ios-cmake-master
        cp $HOME/opt/ios-cmake/ios.toolchain.cmake $HOME/dev/3rdParty/ios-cmake-master/

    - name: Set environment variables for iphoneos arm64
      run: |
        echo "CMTOOLCHAIN=$HOME/dev/3rdParty/ios-cmake-master/ios.toolchain.cmake" >> $GITHUB_ENV
        echo "SDKPATH=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
        echo "PREFIX=$HOME/build/iphoneos_arm64" >> $GITHUB_ENV
        echo "OS=OS64" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH" >> $GITHUB_ENV

    - name: Copy and run build scripts for iphoneos arm64
      run: |
        cp build-sqlite.sh $HOME/
        cp build-proj.sh $HOME/
        cp build-gdal.sh $HOME/
        chmod +x $HOME/build-*.sh
        $HOME/build-sqlite.sh
        $HOME/build-proj.sh
        $HOME/build-gdal.sh --with-png=external --with-jpeg=external --with-gif=external --with-jsonc=external --with-opencad=external --with-lerc=external

    - name: Upload GDAL iOS build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gdal-ios-build
        path: ${{ github.workspace }}/build/iphoneos_arm64/**
    
