name: Generate Frameworks

on:
  workflow_dispatch:


jobs:
  generate-frameworks:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup directories and copy headers
      run: |
        mkdir -p $HOME/build/include_sqlite3 $HOME/build/include_proj $HOME/build/include_gdal
        cp -R ./artifacts/gdal-ios-build/include/* $HOME/build/include_gdal/
        mv $HOME/build/include_gdal/sqlite3* $HOME/build/include_sqlite3/
        mv $HOME/build/include_gdal/proj* $HOME/build/include_proj/

    - name: Generate Frameworks for SQLite3
      run: |
        export FRAMENAME=sqlite3
        export LIBNAME=libsqlite3
        for PLATFORM in ios-arm64 ios-simulator; do
          export FRAMEPATH="$HOME/build/${PLATFORM}/${FRAMENAME}.framework"
          mkdir -p "${FRAMEPATH}/Versions/A/Headers"
          ln -sfh "A" "${FRAMEPATH}/Versions/Current"
          ln -shf "Versions/Current/Headers" "${FRAMEPATH}/Headers"
          ln -sfh "Versions/Current/${FRAMENAME}" "${FRAMEPATH}/${FRAMENAME}"
          cp -a "${HOME}/build/include_${FRAMENAME}/" "${FRAMEPATH}/Versions/A/Headers"
          cp -a "./artifacts/sqlite-proj-${PLATFORM}-build/lib/${LIBNAME}.a" "${FRAMEPATH}/Versions/A/${FRAMENAME}"
        done

    - name: Generate Frameworks for Proj
      run: |
        export FRAMENAME=proj
        export LIBNAME=libproj
        for PLATFORM in ios-arm64 ios-simulator; do
          export FRAMEPATH="$HOME/build/${PLATFORM}/${FRAMENAME}.framework"
          mkdir -p "${FRAMEPATH}/Versions/A/Headers"
          ln -sfh "A" "${FRAMEPATH}/Versions/Current"
          ln -shf "Versions/Current/Headers" "${FRAMEPATH}/Headers"
          ln -sfh "Versions/Current/${FRAMENAME}" "${FRAMEPATH}/${FRAMENAME}"
          cp -a "${HOME}/build/include_${FRAMENAME}/" "${FRAMEPATH}/Versions/A/Headers"
          cp -a "./artifacts/sqlite-proj-${PLATFORM}-build/lib/${LIBNAME}.a" "${FRAMEPATH}/Versions/A/${FRAMENAME}"
        done

    - name: Generate Frameworks for GDAL
      run: |
        export FRAMENAME=gdal
        export LIBNAME=libgdal
        for PLATFORM in ios ios-sim; do
          export FRAMEPATH="$HOME/build/${PLATFORM}/${FRAMENAME}.framework"
          mkdir -p "${FRAMEPATH}/Versions/A/Headers"
          ln -sfh "A" "${FRAMEPATH}/Versions/Current"
          ln -shf "Versions/Current/Headers" "${FRAMEPATH}/Headers"
          ln -sfh "Versions/Current/${FRAMENAME}" "${FRAMEPATH}/${FRAMENAME}"
          cp -a "${HOME}/build/include_${FRAMENAME}/" "${FRAMEPATH}/Versions/A/Headers"
          cp -a "./artifacts/gdal-${PLATFORM}-build/lib/${LIBNAME}.a" "${FRAMEPATH}/Versions/A/${FRAMENAME}"
        done

    - name: Setup XCFramework directory
      run: mkdir "${HOME}/build/xcf"
  
    - name: Generate XCFramework for SQLite3
      run: |
        xcodebuild -create-xcframework \
        -framework "${HOME}/build/ios-arm64/sqlite3.framework" \
        -framework "${HOME}/build/ios-simulator/sqlite3.framework" \
        -output "${HOME}/build/xcf/sqlite3.xcframework"
  
    - name: Generate XCFramework for Proj
      run: |
        xcodebuild -create-xcframework \
        -framework "${HOME}/build/ios-arm64/proj.framework" \
        -framework "${HOME}/build/ios-simulator/proj.framework" \
        -output "${HOME}/build/xcf/proj.xcframework"

    - name: List GDAL Framework for ios-arm64
      run: ls -l "${HOME}/build/ios-arm64/gdal.framework"
   
    - name: List GDAL Framework for ios-simulator
      run: ls -l "${HOME}/build/ios-simulator/gdal
  
    - name: Generate XCFramework for GDAL
      run: |
        xcodebuild -create-xcframework \
        -framework "${HOME}/build/ios-arm64/gdal.framework" \
        -framework "${HOME}/build/ios-simulator/gdal.framework" \
        -output "${HOME}/build/xcf/gdal.xcframework"

    - name: Upload SQLite3 XCFramework as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sqlite3-xcframework
        path: ${HOME}/build/xcf/sqlite3.xcframework
  
    - name: Upload Proj XCFramework as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: proj-xcframework
        path: ${HOME}/build/xcf/proj.xcframework
  
    - name: Upload GDAL XCFramework as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gdal-xcframework
        path: ${HOME}/build/xcf/gdal.xcframework