name: Build and Upload SQLite and Proj for iOS (arm64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13-xlarge

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install cmake
        brew install libtiff
        brew install libgeotiff
        brew install libpng
        brew install jpeg
        brew install qhull
        brew install liblerc
        brew install geos
        git clone https://github.com/leetal/ios-cmake.git $HOME/opt/ios-cmake

    - name: Copy toolchain file
      run: |
        mkdir -p $HOME/dev/3rdParty/ios-cmake-master
        cp $HOME/opt/ios-cmake/ios.toolchain.cmake $HOME/dev/3rdParty/ios-cmake-master/

    - name: Set environment variables for iphoneos arm64
      run: |
        echo "CMTOOLCHAIN=$HOME/dev/3rdParty/ios-cmake-master/ios.toolchain.cmake" >> $GITHUB_ENV
        echo "SDKPATH=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
        echo "PREFIX=$HOME/build/iphoneos_arm64" >> $GITHUB_ENV
        echo "OS=OS64" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH" >> $GITHUB_ENV

    - name: Build and copy scripts for sqlite and proj
      run: |
        cp build-sqlite.sh $HOME/
        cp build-proj.sh $HOME/
        chmod +x $HOME/build-sqlite.sh
        chmod +x $HOME/build-proj.sh
        $HOME/build-sqlite.sh
        $HOME/build-proj.sh

    - name: Upload SQLite and Proj iOS build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sqlite-proj-ios-arm64-build
        path: /Users/runner/build/iphoneos_arm64/**