name: Generate FAT Libraries

on:
  workflow_dispatch:

jobs:
  generate-fat-libraries:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: |
        mkdir -p $HOME/build/fat-libraries

    - name: Download SQLite and Proj iOS Simulator build artifacts
      uses: actions/download-artifact@v2
      with:
        name: sqlite-proj-ios-simulator-build
        path: $HOME/build/iphonesimulator

    - name: Download SQLite and Proj iOS (arm64) build artifacts
      uses: actions/download-artifact@v2
      with:
        name: sqlite-proj-ios-arm64-build
        path: $HOME/build/iphoneos_arm64

    - name: Generate FAT libraries
      run: |
        for LIBNAME in libsqlite3 libproj; do
          lipo -create \
            $HOME/build/iphoneos_arm64/lib/${LIBNAME}.a \
            $HOME/build/iphonesimulator/lib/${LIBNAME}.a \
            -output $HOME/build/fat-libraries/${LIBNAME}.a
        done

    - name: Upload FAT libraries
      uses: actions/upload-artifact@v2
      with:
        name: fat-libraries
        path: $HOME/build/fat-libraries/