name: Generate FAT Libraries

on:
  workflow_dispatch:

jobs:
  generate-fat-libraries:
    runs-on: macos-13-xlarge

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: |
        mkdir -p $HOME/build/fat-libraries

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        path: $HOME/build/

    - name: Generate FAT libraries
      run: |
        for LIBNAME in libsqlite3 libproj libgdal; do
          lipo -create \
            $HOME/build/iphoneos_arm64/lib/${LIBNAME}.a \
            $HOME/build/iphonesimulator/lib/${LIBNAME}.a \
            -output $HOME/build/fat-libraries/${LIBNAME}.a
        done

    - name: Upload FAT libraries
      uses: actions/upload-artifact@v2
      with:
        name: gdal-fat-libraries
        path: $HOME/build/fat-libraries/