name: Generate FAT Libraries

on:
  workflow_dispatch:

jobs:
  generate-fat-libraries:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: |
        mkdir -p $HOME/build/iphoneos/lib $HOME/build/iphonesimulator/lib

    - name: Generate FAT libraries
      run: |
        export LIBNAMES=("libsqlite3" "libproj" "libgdal")
        for LIBNAME in "${LIBNAMES[@]}"; do
          # Generate FAT library for iOS
          lipo -create \
            /artifacts/${LIBNAME}-ios-build/lib/${LIBNAME}.a \
            -output $HOME/build/iphoneos/lib/${LIBNAME}.a
          
          # Generate FAT library for iOS Simulator
          # Assuming there are separate builds for arm64 and x86_64 architectures of the simulator
          lipo -create \
            /artifacts/${LIBNAME}-ios-sim-build/lib/${LIBNAME}_arm64.a \
            /artifacts/${LIBNAME}-ios-sim-build/lib/${LIBNAME}_x86_64.a \
            -output $HOME/build/iphonesimulator/lib/${LIBNAME}.a
        done

    - name: Upload FAT libraries
      uses: actions/upload-artifact@v2
      with:
        name: fat-libraries
        path: |
          $HOME/build/iphoneos/lib
          $HOME/build/iphonesimulator/lib